// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
)

const connectUserAndGroup = `-- name: ConnectUserAndGroup :exec
INSERT INTO
    user_groups (user_id, group_id)
VALUES
    ($1, $2)
`

type ConnectUserAndGroupParams struct {
	UserID  int64 `db:"user_id" json:"user_id"`
	GroupID int64 `db:"group_id" json:"group_id"`
}

func (q *Queries) ConnectUserAndGroup(ctx context.Context, arg ConnectUserAndGroupParams) error {
	_, err := q.db.ExecContext(ctx, connectUserAndGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO
    groups (name, description, group_owner_id)
VALUES 
    ($1, $2, $3)
RETURNING id, name, description, group_owner_id, created_at, updated_at, deleted_at
`

type CreateGroupParams struct {
	Name         string         `db:"name" json:"name"`
	Description  sql.NullString `db:"description" json:"description"`
	GroupOwnerID int64          `db:"group_owner_id" json:"group_owner_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Description, arg.GroupOwnerID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GroupOwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
