// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: item_img.sql

package db

import (
	"context"
)

const insertItemImage = `-- name: InsertItemImage :exec
INSERT INTO item_image
("item_id","image_url")
values
($1, $2)
`

type InsertItemImageParams struct {
	ItemID   int64  `db:"item_id" json:"item_id"`
	ImageUrl string `db:"image_url" json:"image_url"`
}

func (q *Queries) InsertItemImage(ctx context.Context, arg InsertItemImageParams) error {
	_, err := q.db.ExecContext(ctx, insertItemImage, arg.ItemID, arg.ImageUrl)
	return err
}
