// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: item_type.sql

package db

import (
	"context"
	"database/sql"
)

const createItemType = `-- name: CreateItemType :exec
insert into item_type ("name") values ($1)
`

func (q *Queries) CreateItemType(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createItemType, name)
	return err
}

const listAllItemTypes = `-- name: ListAllItemTypes :many
SELECT id, name, created_at, updated_at, deleted_at, parent_id FROM item_type where deleted_at is null
`

func (q *Queries) ListAllItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listAllItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, name, created_at, updated_at, deleted_at, parent_id FROM item_type where deleted_at is null AND parent_id = $1
`

func (q *Queries) ListItemTypes(ctx context.Context, parentID sql.NullInt64) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listItemTypes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMainItemTypes = `-- name: ListMainItemTypes :many
SELECT id, name, created_at, updated_at, deleted_at, parent_id FROM item_type where deleted_at is null AND parent_id is null
`

func (q *Queries) ListMainItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.QueryContext(ctx, listMainItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
