// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: location.sql

package db

import (
	"context"
)

const getLocation = `-- name: GetLocation :one
SELECT id, name, image_url, description, group_id, created_at, updated_at, deleted_at FROM location WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLocation(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Description,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLocationsOfGroup = `-- name: ListLocationsOfGroup :many
SELECT id, name, image_url, description, group_id, created_at, updated_at, deleted_at FROM location WHERE group_id = $1
`

func (q *Queries) ListLocationsOfGroup(ctx context.Context, groupID int64) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocationsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Description,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
