// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: manufacturer.sql

package db

import (
	"context"
)

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name, logo_url, description, created_at, updated_at, deleted_at FROM manufacturer
`

func (q *Queries) ListManufacturers(ctx context.Context) ([]Manufacturer, error) {
	rows, err := q.db.QueryContext(ctx, listManufacturers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Manufacturer
	for rows.Next() {
		var i Manufacturer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
