// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type User struct {
	ID     int64          `db:"id" json:"id"`
	Name   string         `db:"name" json:"name"`
	Email  string         `db:"email" json:"email"`
	Avatar sql.NullString `db:"avatar" json:"avatar"`
}
